name: Linters

on:
  push:
    branches:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    name: Install and validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and run code validation
        run: npm run setup:ci
